name: Add or remove maintenance labels

on:
  pull_request:
    types: [opened, edited]
    branches: [master] # target branch

env:
  TARGET_RELEASE: 13.x

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: "Add target label"
        if: ${{ contains(github.event.pull_request.body, 'BREAKING CHANGE:') }}=
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "target: ${{ env.TARGET_RELEASE }}"
      - name: "Remove target label"
        if: ${{ !contains(github.event.pull_request.body, 'BREAKING CHANGE:') }}=
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "target: ${{ env.TARGET_RELEASE }}"
